project_id = "qvunaswogfwhixecjpcn"

[functions.enqueue]
verify_jwt = true

[functions.heartbeat]
verify_jwt = true

[functions.leave_queue]
verify_jwt = true

[functions.matchmaker_tick]
verify_jwt = false

[functions.cleanup_queue]
verify_jwt = false

[functions.game-ws]
verify_jwt = false

[functions.admin-auth]
verify_jwt = true

[edge_runtime.cron.matchmaker]
name = "matchmaker_tick"
schedule = "*/2 * * * * *"

[edge_runtime.cron.cleanup]
name = "cleanup_queue"
schedule = "*/30 * * * * *"